spring.application.name=itoup

spring.datasource.url=jdbc:postgresql://localhost:5432/requestsITOUP
spring.datasource.username=postgres
spring.datasource.password=QueenP2502
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
